# Generated by Django 6.0.4 on 2026-04-22 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated unique reference number for this complaint', max_length=20, unique=True)),
                ('reporter_name', models.CharField(help_text='Full name of the person reporting the issue', max_length=100)),
                ('reporter_email', models.EmailField(help_text='Email address for complaint status updates', max_length=254)),
                ('reporter_phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15)),
                ('location_text', models.CharField(help_text="Describe the location (e.g., 'Near Sector 5 Market, Noida')", max_length=300)),
                ('google_maps_link', models.URLField(blank=True, help_text='Paste Google Maps link for precise location (optional)')),
                ('description', models.TextField(help_text='Detailed description of the garbage issue')),
                ('image', models.ImageField(help_text='Upload a photo of the garbage issue for evidence', upload_to='complaints/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', help_text='Current status of the complaint', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the complaint', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text='Internal remarks by municipal authority staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (optional — anonymous submissions allowed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garbage Complaint',
                'verbose_name_plural': 'Garbage Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
